### ISSUE TITLE
Bluetooth Classic Master

### ISSUE THREAD

**Issue by flowersnlyrics** [cypresssemiconductorco/CypressAcademy_BT101_Files#3]
I cannot find any documentation or examples relating to how to connect two of these boards with Bluetooth classic rather than BLE.  I have posted on the forums, and the only help provided is with the Bluetooth Classic Slave configuration in the SPP profile. No one has provided a Bluetooth classic master example, or any directions on how to configure a Bluetooth Classic master using the API provided.

**Comment by greglandry** [comment]
For our broad market offering we only support the SPP slave profile.

**Comment by flowersnlyrics** [comment]
Is there an example that offers support for Bluetooth classic master on *any* profile??

**Comment by AnjanaMuralidharan** [comment]
Hi,

In BT classic , we provide options for profile level of connection , rather than a BLE GATT level connection. Which means depending upon the BT classic profile you want to use , we can give you directions. 
We do not have any examples for BT classic master. In BT classic you need to start inquiry and paging process to establish a connection and communicate. As mentioned above , there is only profile level of connection APIs available for 20819. 

For example , suppose you want to use SPP profile, you may try below steps for Master side: 

1. Start an inquiry if peer device address is unknown . API wiced_bt_start_inquiry (check wiced_bt_dev.h file for API details) 
2. inquiry scan call back will list all the peer BT classic devices 
3. You can send a pair request to the concerned peer device if needed . API wiced_bt_dev_sec_bond 
4. You can send SPP profile level connection Spp connect . Check API wiced_bt_spp_connect in spp_lib.c 
 
Thanks,
Anjana

**Comment by AnjanaMuralidharan** [comment]
In WICED SDK , You may also refer to hci_audio_gateway demo for implementation. ( /20719-B1_Bluetooth/apps/demo/hci_audio_gateway )
